### ISSUE TITLE
Firefox: Map is blank

### ISSUE THREAD

**Issue by stdavis** [agrc/wri-web#110]
![image](https://cloud.githubusercontent.com/assets/1326248/10225168/b0162b00-681e-11e5-8e30-49726812775d.png)

**Comment by steveoh** [comment]
closed as duplicate of #108 and it's not just firefox.

**Comment by stdavis** [comment]
I'm not sure this is a duplicate. Firefox fails for me everytime. Other browsers are drawing fine for me 95% of the time. Tested Safari, Chrome, FF and IE11.

**Comment by steveoh** [comment]
if you open the dev tools in firefox, it will start working if you set debug points or something. I can't remember what the trigger was.
