### ISSUE TITLE
Action parsing

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#116]
actions aren't parsed unless they are created. you have to hit add additional action to get it to show up which isn't possible on features other than terrestrial and aquatic. It seems like a UX problem if you are going to parse what is in the drop downs and the added buckets.

**Comment by stdavis** [comment]
I went over this with Aaron and this was his recommendation. You'll notice that the save button is not enabled unless there is an existing action (blue box) or if the required fields for a new action are filled out.

However, I did overlook grabbing the data if the add additional action button hasn't been clicked yet. I'll do that this morning.
