### ISSUE TITLE
Empty Actions

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#129]
Please don't send empty actions

![image](https://cloud.githubusercontent.com/assets/325813/10436634/dfdf200c-70e4-11e5-9238-cd687b8111fd.png)

**Comment by stdavis** [comment]
@steveoh How do I reproduce this?

**Comment by stdavis** [comment]
So I should return null for actions for affected areas?

**Comment by steveoh** [comment]
An empty list is being sent currently. I would prefer null.
