### ISSUE TITLE
Improve related table data

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#148]
From aaron,

> I prefer option 2 or 3.  Both are simple.  I don't mind option 1, but it might seem like a bit much on the eyes.  I think having one well/div would be easier on the eyes.  With option 3 I would place the "sections" in the order that I have laid out (county, focus area, land ownership and stream miles.

![image](https://cloud.githubusercontent.com/assets/325813/10677785/af0e2858-78cb-11e5-821c-9e604af9d625.png)

**Comment by stdavis** [comment]
I would vote for #2 without the well at all FWIW.
