### ISSUE TITLE
loading graphic

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#149]
the loading graphic should hide when a project isn't found.

![image](https://cloud.githubusercontent.com/assets/325813/10678517/2f1465ae-78d0-11e5-828d-5007a41e2952.png)

**Comment by stdavis** [comment]
@steveoh: How are you reproducing? When I try to load that project id I get the following error from the API (master):
```
Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at wri_webapi.ProjectModule.<>c__DisplayClass1f.<<.ctor>b__b>d__33.MoveNext() in c:\Projects\wri-webapi\wri-webapi\ProjectModule.cs:line 71
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

Looks like `response.Project` is `null`.

The front end just toasts that there was an error with the project api and doesn't every show the "We could not find a project with the id: 3" message.

**Comment by steveoh** [comment]
Update to the latest pr of the web api
