### ISSUE TITLE
feature editing

### ISSUE THREAD

**Issue by stdavis** [agrc/wri-web#154]
@steveoh: I'd like some feedback on this...

What if, when the user clicks the "Modify Feature" button (which will show up next to the "Delete Feature" button), we load all of the data into what is now called the `NewFeatureWizard` widget (it would obviously need to be renamed)? The widget would look the same as it does when the user is creating a new feature after they are done filling in all of the data and defining the geometry. With all of the existing actions added and the geometry defined like this:

![image](https://cloud.githubusercontent.com/assets/1326248/10705426/11df7430-799b-11e5-928a-5f206b95a8fc.png)

We could update the name of the tab and the text in the save button to enforce the idea that they are editing an existing feature. Then we could send the data to the edit service instead of the create feature service.

**Comment by steveoh** [comment]
I like this idea. Then you could click on the blue boxes and modify values. We could change the color of the box and fire off the update. If they wanted to change geometry then we could have a save changes button.

**Comment by stdavis** [comment]
I'll start working on this.
