### ISSUE TITLE
reference layer update script

### ISSUE THREAD

**Issue by stdavis** [agrc/wri-web#166]
Create script to update the reference layer data and deploy to server.

**Comment by steveoh** [comment]
This is fouling up some things from the wri_focus_areas. Is this coming from the source data or something with the update script?


![image](https://cloud.githubusercontent.com/assets/325813/11829196/13da4620-a358-11e5-8e96-d92b50d18028.png)

**Comment by steveoh** [comment]
It's there data...

**Comment by steveoh** [comment]
The update script has been failing. It appears the relative path for finding the database connections is making the `arcpy.ListDatasets()` method return `None`.

**Comment by stdavis** [comment]
The only problem that I found was that I fat fingered the path in the scheduled task. I tested the script after I deployed it at the command line but failed to do so via the scheduler. Lesson learned. I ran the task successfully via the scheduler this morning and it ran with no issues.

I did see the errors from your testing last night. Not sure how you got that to happen other than maybe you ran the script from a folder other than the one that it is in?

I also verified that the script is running successfully on the test server.

**Comment by steveoh** [comment]
I ran the script from the arcgis python folder since python is not in the path on that machine. If it only works a certain way manually, can you document that on the readme.

**Comment by stdavis** [comment]
It works if you just run `main.py`.

On Thu, Dec 17, 2015 at 9:37 AM, steveoh <notifications@github.com> wrote:

> I ran the script from the arcgis python folder since python is not in the
> path on that machine. If it only works a certain way manually, can you
> document that on the readme.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/wri-web/issues/166#issuecomment-165503917>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@SThomasDavis <https://twitter.com/SThomasDavis>
