### ISSUE TITLE
Retreatment

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#181]
Retreatment was set to `Y` on an affected area modify. The UI does not show the checkbox but it was sent with the request payload.

```
category:Affected Area
retreatment:Y
```

**Comment by stdavis** [comment]
I thought that retreatment was only valid for Terrestrial and Aquatic Treatment categories. Do I need to add it to Affected Areas also?

**Comment by steveoh** [comment]
It is only valid on those types. The bug is that it was sent as y on affected area.

**Comment by stdavis** [comment]
Oh, now I see. What should it send? Nothing? Null? N?

**Comment by steveoh** [comment]
I think N
