### ISSUE TITLE
software version does not support import of wkb geometry collections

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#204]
Uploading a shapefile and the API is returning `this software version does not support import of wkb geometry collections`

**Comment by steveoh** [comment]
this error is being thrown from [this arcobjects call](https://github.com/agrc/wri-webapi/blob/master/wri-soe/wri-soe.cs#L138). i don't have any great ideas at the moment but I will keep on it.

**Comment by steveoh** [comment]
it appears to be a bug in arcobjects based on the size of the multipolygon created by this shapefile upload. I removed vertices from the WKT that is generated and the issue goes away. I opened a support ticket with esri and will see what happens.

**Comment by steveoh** [comment]
Ok so it is not a bug in the esri software. It was created by [our solution](https://github.com/agrc/wri-web/commit/4a47a1d93dbad954175a20236a626329296ce6ab) for https://github.com/agrc/wri-web/issues/204. 

The polygon coordinates below were rounded to two decimal places. If you look closely, there are 4 instances of the coordinate `-12276401.01 4999737.43`; One being the start and one being the end. The other two are causing this shape to be considered a `LINESTRING` because they self intersect? and the entire geometry is considered a `GeometryGollection` which is not supported in esri land.

` POLYGON ((-12276401.01 4999737.43, -12276401.02 4999737.42, -12276401.07 4999737.31, -12276401.03 4999737.3, -12276401.02 4999737.42, -12276401.01 4999737.43, -12276401.01 4999737.41, -12276401 4999737.46, -12276401.01 4999737.43, -12276401.01 4999737.43, -12276400.39 4999744.7, -12276394.35 4999750.39, -12276389.62 4999759.44, -12276374.82 4999776.4, -12276374.64 4999776.68, -12276374.36 4999776.94, -12276374.28 4999777.19, -12276355.55 4999789.41, -12276335.06 4999815.86, -12276312.64 4999834.69, -12276280.17 4999858.91, -12276267.69 4999863.19, -12276255.72 4999863.19, -12276236.37 4999883.22, -12276230.82 4999882.25, -12276222.8 4999857.44, -12276218.73 4999840.83, -12276219.21 4999824.25, -12276222.09 4999813.09, -12276220.6 4999806.42, -12276240.32 4999791, -12276252.88 4999782.48, -12276269.7 4999772.08, -12276287.01 4999765.68, -12276302.96 4999752.45, -12276333.84 4999729.81, -12276340.47 4999723.22, -12276351.63 4999714.14, -12276363.8 4999707.81, -12276377.47 4999689.84, -12276378.58 4999678.02, -12276374.4 4999660.85, -12276369.57 4999647.22, -12276367.4 4999624.88, -12276372.43 4999614.44, -12276393.39 4999613.14, -12276403.95 4999618.96, -12276413.04 4999619.28, -12276423.71 4999607.91, -12276423.5 4999607.83, -12276425.44 4999588.9, -12276425.86 4999570.76, -12276421.52 4999556.24, -12276421.7 4999555.75, -12276413.37 4999536.3, -12276406.45 4999513.36, -12276399.06 4999504.16, -12276384.07 4999472.72, -12276378.85 4999446.81, -12276367.43 4999424.46, -12276348.28 4999405.16, -12276335.5 4999387.91, -12276327.03 4999381.22, -12276298.76 4999368.8, -12276277.03 4999365.12, -12276257.94 4999354.35, -12276253.75 4999344.99, -12276246.94 4999336.76, -12276239.67 4999325.87, -12276222.69 4999308.11, -12276200.38 4999294.95, -12276181.47 4999290.26, -12276187.29 4999277.81, -12276189.79 4999269.79, -12276205.83 4999271.84, -12276220.58 4999279.74, -12276220.77 4999279.86, -12276236.75 4999287.54, -12276257.53 4999297.51, -12276266.73 4999309.77, -12276288.3 4999324.98, -12276306.22 4999340.09, -12276321.05 4999350.42, -12276341.53 4999354.42, -12276368.2 4999361.49, -12276386.22 4999368.87, -12276400.86 4999377.98, -12276411.34 4999385.01, -12276432.39 4999391.98, -12276455.57 4999395.1, -12276469.14 4999401.03, -12276488.49 4999409.53, -12276516.39 4999414.54, -12276530.55 4999420.88, -12276557.42 4999431.52, -12276569.84 4999436.47, -12276586.07 4999436.24, -12276585.86 4999450.05, -12276572.64 4999468.01, -12276563.18 4999485.5, -12276537.27 4999512.33, -12276524.78 4999527.03, -12276512.71 4999545.87, -12276495.09 4999569.56, -12276484.13 4999590.76, -12276468.92 4999611.45, -12276455.23 4999627.51, -12276448.79 4999644.19, -12276428.05 4999664.49, -12276423.4 4999684.12, -12276417.63 4999699.56, -12276414.95 4999716.73, -12276401.01 4999737.43))`

**Comment by stdavis** [comment]
Wow. Nice sleuthing!

My thoughts:
Removing duplicate points seems like a bad idea to me. You couldn't be sure how that would change the shape (and area) of the polygon.

The stored procedure seems like the ideal solution to me. Then we know that the data isn't changed at all. Although I could see increasing the number of decimal places being a quick and easy fix if it works with https://github.com/agrc/wri-webapi/issues/12.

Looks like [we do check for self intersecting polygons](https://github.com/agrc/wri-web/blob/master/scripts/ZipToGraphics/zipToGraphics.py#L55-L58) but that happens before the rounding.

**Comment by steveoh** [comment]
The stored procedure for rounding is slow enough that I would say it is unusable.

Increasing the decimal precision seems like a a quick fix but I think a better solution can come from upstream.

[Generalizing](http://desktop.arcgis.com/en/arcmap/latest/tools/editing-toolbox/generalize.htm) the polygons should fix the issue of creating invalid shapes from dropping 2 decimal places. If no two points are that close then there is no problem. It is also a simple fix. Do you have any issues with that?

_I'm not worried about modifying the shape since we are already modifying the shape by rounding._
