### ISSUE TITLE
css and feature colors do not match

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#49]
![image](https://cloud.githubusercontent.com/assets/325813/9095685/ccf9c20c-3b75-11e5-9da8-9d31009607ac.png)

**Comment by stdavis** [comment]
This also happens with the project details:
![image](https://cloud.githubusercontent.com/assets/1326248/9097665/17c710d0-3b82-11e5-8665-0456f47adb60.png)

These colors come from `dnr-style.css`.

**Comment by stdavis** [comment]
Aaron has made these changes.
