### ISSUE TITLE
Google imagery dev/at url

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#69]
we need the urls from rick. i pushed a build not realizing the url was not in the config.

**Comment by stdavis** [comment]
Isn't this what you are talking about? https://github.com/agrc/wri-web/blob/master/src/app/config.js#L30

**Comment by steveoh** [comment]
regexp: https?:\/\/wri\.utah\.gov(\/.*)?|https?:\/\/wri\.\w*\.utah\.gov(\/.*)? 

I didn't catch the \w that would allow for at and dev
