### ISSUE TITLE
Feature Grid row unclickable

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#79]
I can't get the row click event to fire when there is only a single feature in the grid. Therefore the details panel can't be displayed.

[repro project](https://wri.at.utah.gov/wri/map/map.html#id=2162)

**Comment by stdavis** [comment]
@steveoh I wonder if this is a database issue. This same project works correctly on my vm and also in dev: https://wri.dev.utah.gov/wri/map/map.html#id=2162
