### ISSUE TITLE
Project Title

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-web#96]
I think we should consider removing and letting it wrap at `260px`.

```css
.project-details .title {
    /* text-overflow: ellipsis; */
    /* overflow: hidden; */
    /* white-space: nowrap; */
}
```

I think it looks ok that way and doesn't hide the project number.

**Comment by stdavis** [comment]
I'm good with this...

![image](https://cloud.githubusercontent.com/assets/1326248/10167565/458d59a0-6686-11e5-941b-8e79d8869d43.png)
